<?php
// this code is autogenerated
namespace Revobot\Commands;

use Revobot\Revobot;
use Revobot\Money\Revocoin;

class CasinoCmd extends BaseCmd
{
    const KEYS = ['casino','казино',];
    const IS_ENABLED = true;
    const HELP_DESCRIPTION = 'Казино на ревокоены';
    private Revobot $bot;

    public function __construct($input, Revobot $bot)
    {
        parent::__construct($input);
        $this->bot = $bot;
        $this->setDescription("/casino сумма или все");
    }

    public function exec(): string
    {

        if (empty($this->input)) {
            return $this->description;
        }

        $user_balance = (float)(new Revocoin($this->bot))->getBalance($this->bot->getUserId());
        // if input string all or все or всё - amount is user balance
        if ($this->input === 'all' || $this->input === 'все' || $this->input === 'всё') {
            $amount = $user_balance;
        } else {
            $amount = (float)$this->input;
        }

        // get balance of TG_BOT_ID (bank)
        $balance = (new Revocoin($this->bot))->getBalance(-TG_BOT_ID);


        // check that amount is positive and user has enough money
        if ($amount <= 0) {
            return 'Неверная сумма';
        }

        if(($user_balance < $amount) ||( $user_balance == 0)) {
            return 'Недостаточно средств у вас на счету';
        }

        $coeff_arr = [0, 0, 2, 3, 4, 5, 0, 2, 2, 2, 3, 4, 5, 6, 0, 2, 3, 4, 5, 6, 10, 2, 3, 4, 5, 0, 0, 50, 1];
        $coeff = $coeff_arr[mt_rand(0, count($coeff_arr)-1)];

        if ($balance < ($amount * $coeff)) {
            $coeff = 0;
      //      return 'Недостаточно средств на счету казина';
        }

        $old_amount = $amount;
        $new_amount = $amount * $coeff;
        if($new_amount == 0){
            (new Revocoin($this->bot))->transaction(
                $old_amount,
                -TG_BOT_ID,
                $this->bot->getUserId()
            );
            return '-' . $old_amount . ' R';
        }else{
            (new Revocoin($this->bot))->transaction(
                $new_amount,
                $this->bot->getUserId(),
                -TG_BOT_ID
            );
            $commission = $new_amount * Revocoin::TRANSACTION_COMMISSION;
            $new_amount -= $commission;

            return '+' . $new_amount . ' R';
        }
    }
}
