<?php
// this code is autogenerated
namespace Revobot\Commands;

use Revobot\Revobot;
use Revobot\Money\Revocoin;

class CasinoCmd extends BaseCmd
{
    const KEYS = ['casino','казино',];
    const IS_ENABLED = true;
    const HELP_DESCRIPTION = 'Казино на ревокоены';
    private Revobot $bot;

    public function __construct($input, Revobot $bot)
    {
        parent::__construct($input);
        $this->bot = $bot;
        $this->setDescription("/casino сумма или все");
    }

    public function exec(): string
    {

        if (empty($this->input)) {
            return $this->description;
        }

        $user_balance = (float)(new Revocoin($this->bot))->getBalance($this->bot->getUserId());
        // if input string all or все or всё - amount is user balance
        if ($this->input === 'all' || $this->input === 'все' || $this->input === 'всё') {
            $amount = $user_balance;
        } else {
            $amount = (float)$this->input;
        }

        // get balance of TG_BOT_ID (bank)
        $balance = (new Revocoin($this->bot))->getBalance(-TG_BOT_ID);
        if ($balance < $amount) {
            return 'Недостаточно средств на счету';
        }

        // check that amount is positive and user has enough money
        if ($amount <= 0) {
            return 'Неверная сумма';
        }

        if(($user_balance < $amount) ||( $user_balance == 0)) {
            return 'Недостаточно средств на счету';
        }

        $rand = mt_rand(0, 100);
        (new Revocoin($this->bot))->transaction($amount,  -TG_BOT_ID,$this->bot->getUserId(),);

        // there is different random and coefficient pseudo-randomly
        /** @var float[] $coefficient_array */
        $coefficient_array = [
            0,
            0.1,
            0.2,
            0.3,
            0.4,
            0.5,
            0.6,
            0.7,
            0.8,
            0.9,
            1,
            1.1,
            1.2,
            1.3,
            1.4,
            1.5,
            1.6,
            1.7,
            1.8,
            1.9,
            2,
            2.1,
            2.2,
            2.3,
            2.4,
            2.5,
            2.6,
            2.7,
            2.8,
            2.9,
            3,
        ];
        $coefficient = $coefficient_array[$rand % count($coefficient_array)];
        if ($rand > 50) { // if user won
            (new Revocoin($this->bot))->transaction(
                $amount + ($amount * $coefficient),
                $this->bot->getUserId(),
                -TG_BOT_ID
            );
            return '+' . ($amount + ($amount * $coefficient)) . ' R';
        } else { // if user lost
            (new Revocoin($this->bot))->transaction(
                $amount * $coefficient,
                -TG_BOT_ID,
                $this->bot->getUserId()
            );
            return '-' . $amount * $coefficient . ' R';
        }
    }
}
